### ISSUE TITLE
Failed to verify authentication token: 401 Unauthorized

### ISSUE THREAD

**Issue by mborko** [archlinux/arch-boxes#43]
I am not able to build the box, because of this error. Here is the command:

```
$ packer build -debug -only=vmware-iso -var-file=local.json vagrant.json
Debug mode enabled. Builds will not be parallelized.
vmware-iso output will be in this color.

1 error(s) occurred:

* Failed to verify authentication token: 401 Unauthorized
```

My local.json:
```
{
    "iso_url": "https://mirror.rackspace.com/archlinux/iso/latest/archlinux-2019.08.01-x86_64.iso",
    "iso_checksum_url": "https://mirror.rackspace.com/archlinux/iso/latest/sha1sums.txt",
    "iso_checksum_type": "sha1",
    "disk_size": "20480",
    "memory": "8192",
    "cpus": "2",
    "headless": "true",
    "vagrant_cloud_token": "archlinux-ima",
    "write_zeroes": "",
    "boot_wait": "60s"
}
```

Can you help me to solve this problem? What am I missing?

**Comment by shibumi** [comment]
Your vagrant-cloud-token is wrong.. the problem is that we don't support builds without vagrant cloud support yet. 

So how to solve your problem? You need to modify the vagrant.json file, I guess it should work if you just remove the post processor section that uploads the image to the vagrant cloud.

So instead of having this in your post-processors array:
```yaml
    "post-processors": [
        [
            {
                "type": "vagrant",
                "keep_input_artifact": false,
                "output": "Arch-Linux-x86_64-{{ .Provider }}-{{isotime \"2006-01-02\"}}.box"
            },
            {
                "type": "vagrant-cloud",
                "only": ["virtualbox-iso"],
                "access_token": "{{user `vagrant_cloud_token`}}",
                "box_tag": "archlinux/archlinux",
                "version": "{{isotime \"2006.01.02\"}}"
            },
            {
                "type": "vagrant-cloud",
                "only": ["qemu"],
                "access_token": "{{user `vagrant_cloud_token`}}",
                "box_tag": "archlinux/archlinux",
                "version": "{{isotime \"2006.01.02\"}}"
            },
            {
                "type": "vagrant-cloud",
                "only": ["vmware-iso"],
                "access_token": "{{user `vagrant_cloud_token`}}",
                "box_tag": "archlinux/archlinux",
                "version": "{{isotime \"2006.01.02\"}}"
            }
        ]
```

you need something like this:

```yaml
    "post-processors": [
        [
            {
                "type": "vagrant",
                "keep_input_artifact": false,
                "output": "Arch-Linux-x86_64-{{ .Provider }}-{{isotime \"2006-01-02\"}}.box"
            }
        ]
```
